### ISSUE TITLE
Design feedback (Feb.29, 2024)

### ISSUE THREAD

**Issue by LisaHuang2017** [YADAMSS/Matemasie-Font#29]
This is the design feedback for Matemasie, from its latest update as of Feb. 29, 2024.
[Matemasie_LH_feedback_290224.pdf](https://github.com/YADAMSS/Matemasie-Font/files/14448939/Matemasie_LH_feedback_290224.pdf)

- [x] 1. /Germandbls (aside from the suggestions mentioned in issue #28 ) could also be wider to match better with the wide proportions of Matemasie
- [x] 2. some diacritics should have inverted weight distribution (especially tilde and breve)
- [x] 3. the bar of /Hbar needs to be thinner, as thin (or more) as its horizontal bar
- [x] 4. and 8. watch out for alignments of some diacritics, especially the caron on top of /Dcaron that lies too much on the left, or 
/acircumflex with circumflex too much on the right
- [x] 5. /Scaron should be a capital /S with a caron, instead of lowercase s 
- [x] 6. /eth can be wider
- [x] 7. top part of /germandbls can be darker
- [x] 9. watch out for spacing values on multiple glyphs, or kerning whenever it is necessary
- [x] 10. macron looks too big as a diacritic here with lowercase letters. All diacritics have to match in terms of weight
- [x] 11. /idotless (and /jdotless) still have a dot, and shouldn't
- [x] 12. lowercase /r is too dark, if you reduce the weight of the ear it could solve that
- [x] 13. the top of /t is too high (it lies halfway in between x-height and ascenders), and the horizontal bar could be darker
- [x] 14. the height of the currency symbols need to match with the figures
- [x] 15. /greater and /less signs seem too light and placed too low

General comments:
- [x] you can keep the same spacing value for any related glyph instead of adding them manually (ex.: for /O letters with diacritics, or even every letters with a rounded side like the /O, you can enter "O" on the relevant side so it copies the same spacing value as /O 🙂)

**Comment by YADAMSS** [comment]
Hi  Lisa ,
Thank you for your feedback. I will correct them as soon as possible.

**Comment by n8willis** [comment]
Because Lisa mentioned spacing & kerning above, here are the glyphs that I think need some spacing attention:

- [ ] `l` (lowercase L): too much space on the right; the "tail" should get very little, perhaps as little as `x`
- [ ] `f`: too much space on the right; it is OK for it to overhang the bounds on the right slightly. You will just have to look for collisions and use kerning to fix any pairs that collide with `f`.
- [ ] `f`: not enough space on the left. Try to make this adjustment and the one above at the same time; moving the entire glyph to the right slightly (where it is in the middle in some test words) may be all that is needed.
- [ ] `h`: not enough space on the left
- [ ] `t`: too much space on both sides; the left side is better -- perhaps as Lisa suggests you could just set it equal to another glyph. The "open counter" side on the right traps extra space on that side; it should be similar to `c`
- [ ] `F`, `G`, `R`, `T`: too much space on the right when they are next to a lowercase letter. Because most of the letterforms are wider on the top half, they can accidentally create larger "trapped" spaces in the lower half when they are in a two-letter sequence. I think that is the issue with these.
- [ ] `P`, `B`: also too much space on the right, but these are only slightly too much.

Like Lisa recommends, it would be good for consistency -- and require less of your time -- to set several of the glyphs' sidebearings to be defined as equal to another's. You can break the set of glyphs (lowercase and capitals separate) into a few groups that each have the same basic shape on the left and set their left sidebearings to be equal to a standard glyph. Then do the same for the right sides.

The usual recommendations for these standards are 'n' and 'o' and 'v' for the basic straight/round/diagonal side shapes. Matemasie's design is non-traditional, though, so you may want to split the set of glyphs up differently. I notice that the letters with one stem have a different angle than the letters that have two, for example. So in a traditionalist design, `h` and `l` would have the same left sidebearings because of their shapes, in Matemasie, the left side of `l` must be different because it stands more vertically. Picking the standards might be tricky; I just suggest not using the glyphs that I listed above here as the standards, since I think they are the ones requiring changes. 

You could do a session just dedicated to deciding on those categories and setting up the sidebearing formulas, then commit  and let the GitHub Actions build new fonts to test with. It's often helpful to separate the spacing task from the drawing task like that. If you do it, you could do that first, then afterwards go back and look at this of glyphs I put above here. It might be that regularizing them to standards solves most of the concerns.

**Comment by YADAMSS** [comment]
Thank you for your feedback Nate.

**Comment by YADAMSS** [comment]
@LisaHuang2017 
2. some diacritics should have inverted weight distribution (especially tilde and breve),
 Could you please be more specific?

**Comment by tphinney** [comment]
See the markup in red in the PDF for more details. 

Basically, if the tilde has uneven weight, the heaviest part should be the diagonal, rather than it being the two horizontal bits. I agree; the current tilde looks weird enough that it is starting to be a problem.

On the other hand, for the breve, Lisa is suggesting the heaviest part should be at the bottom instead of the sides. Here I don’t have a strong opinion myself; the heavy-sided breve is normal in Cyrillic characters, and unusual in Latin fonts, but it also kind of goes with the general “top weighted” feel of the typeface. The breve is not so weird that I wonder what the heck it is. (Maybe I am biased due to familiarity with Cyrillic though?)

**Comment by YADAMSS** [comment]
thank you @tphinney ,I had not paid attention to the PDF🙂), I see now @LisaHuang2017  !
